// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibeTest.Server.Data;

#nullable disable

namespace VibeTest.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815185817_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("QuestionId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_answers_question_id_order");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.ApplicationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("integer")
                        .HasColumnName("answer_id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_application_results");

                    b.HasIndex("AnswerId")
                        .HasDatabaseName("ix_application_results_answer_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_application_results_question_id");

                    b.HasIndex("ApplicationId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_application_results_application_id_question_id");

                    b.ToTable("application_results", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("TestId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_questions_test_id_order");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("integer")
                        .HasColumnName("answer_id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_results");

                    b.HasIndex("AnswerId")
                        .HasDatabaseName("ix_results_answer_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_results_question_id");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_results_test_id");

                    b.HasIndex("UserId", "TestId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_results_user_id_test_id_question_id");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("QuestionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("questions_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tests");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_tests_author_id");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.TestApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HideResultsFromParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hide_results_from_participant");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_user_id");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_test_applications");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_test_applications_author_id");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_test_applications_recipient_user_id");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_test_applications_test_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_test_applications_token");

                    b.ToTable("test_applications", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.UserTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answer");

                    b.Property<int>("IncorrectAnswer")
                        .HasColumnType("integer")
                        .HasColumnName("incorrect_answer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_test_results");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_user_test_results_test_id");

                    b.HasIndex("UserId", "TestId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_test_results_user_id_test_id");

                    b.ToTable("user_test_results", (string)null);
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Answer", b =>
                {
                    b.HasOne("VibeTest.Server.Models.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.ApplicationResult", b =>
                {
                    b.HasOne("VibeTest.Server.Models.Entities.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_results_answers_answer_id");

                    b.HasOne("VibeTest.Server.Models.Entities.TestApplication", "Application")
                        .WithMany("Results")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_results_test_applications_application_id");

                    b.HasOne("VibeTest.Server.Models.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_results_questions_question_id");

                    b.Navigation("Answer");

                    b.Navigation("Application");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Question", b =>
                {
                    b.HasOne("VibeTest.Server.Models.Entities.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_tests_test_id");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("VibeTest.Server.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Result", b =>
                {
                    b.HasOne("VibeTest.Server.Models.Entities.Answer", "Answer")
                        .WithMany("Results")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_results_answers_answer_id");

                    b.HasOne("VibeTest.Server.Models.Entities.Question", "Question")
                        .WithMany("Results")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_results_questions_question_id");

                    b.HasOne("VibeTest.Server.Models.Entities.Test", "Test")
                        .WithMany("Results")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_tests_test_id");

                    b.HasOne("VibeTest.Server.Models.Entities.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_users_user_id");

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Test", b =>
                {
                    b.HasOne("VibeTest.Server.Models.Entities.User", "Author")
                        .WithMany("AuthoredTests")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tests_users_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.TestApplication", b =>
                {
                    b.HasOne("VibeTest.Server.Models.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_applications_users_author_id");

                    b.HasOne("VibeTest.Server.Models.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_applications_users_recipient_user_id");

                    b.HasOne("VibeTest.Server.Models.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_applications_tests_test_id");

                    b.Navigation("Author");

                    b.Navigation("Recipient");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.UserTestResult", b =>
                {
                    b.HasOne("VibeTest.Server.Models.Entities.Test", "Test")
                        .WithMany("UserTestResults")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_test_results_tests_test_id");

                    b.HasOne("VibeTest.Server.Models.Entities.User", "User")
                        .WithMany("UserTestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_test_results_users_user_id");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Answer", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");

                    b.Navigation("UserTestResults");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.TestApplication", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("VibeTest.Server.Models.Entities.User", b =>
                {
                    b.Navigation("AuthoredTests");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Results");

                    b.Navigation("UserTestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
